host: "127.0.0.1"
port: 8312
auth-dir: "/Users/baobaobao/wangda/.cli-proxy-api"
proxy-url: ""
api-keys:
  - "quotio-local-63D186A8-221A-42B2-B468-E1F29E3AF697"
remote-management:
  allow-remote: false
  secret-key: "$2a$10$mNIg1IN3eFuFwWG9tVWEvu2mZBgv03uvGUaK3bcZKhO20z9cQ5dj6"
  panel-github-repository: https://github.com/router-for-me/Cli-Proxy-API-Management-Center
debug: false
logging-to-file: false
usage-statistics-enabled: true
routing:
  strategy: "fill-first"
quota-exceeded:
  switch-project: true
  switch-preview-model: true
request-retry: 3
max-retry-interval: 30
# Custom Providers (managed by Quotio)

claude-api-key:
  - api-key: "sk-719baed76a9c1d043047d1d281157029"
    base-url: "http://localhost:23000"
oauth-model-alias:
  antigravity:
    - name: rev19-uic3-1p
      alias: gemini-2.5-computer-use-preview-10-2025
    - name: gemini-3-pro-image
      alias: gemini-3-pro-image-preview
    - name: gemini-3-pro-high
      alias: gemini-3-pro-preview
    - name: gemini-3-flash
      alias: gemini-3-flash-preview
    - name: claude-sonnet-4-5
      alias: gemini-claude-sonnet-4-5
    - name: claude-sonnet-4-5-thinking
      alias: gemini-claude-sonnet-4-5-thinking
    - name: claude-opus-4-5-thinking
      alias: gemini-claude-opus-4-5-thinking
